name: CI Frontend

on:
  pull_request:
    paths:
      - "hangman-front/**"

jobs:
  ci:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: hangman-front/package-lock.json

      - name: Install dependencies
        working-directory: hangman-front
        run: npm ci

      - name: Build project
        working-directory: hangman-front
        run: npm run build

      - name: Run unit tests
        working-directory: hangman-front
        run: npm test
